### ISSUE TITLE
Mage.php file sometimes not recreated

### ISSUE THREAD

**Issue by floodedcodeboy** [AydinHassan/magento-core-composer-installer#11] opened 2015-06-05 22:24 UTC
Hi

[original issue](https://github.com/Cotya/magento-composer-installer/issues/25) 

I'm at a point now where intermittently when using `composer update` after adding additional modules to the Mage.php file ends up missing. I'm using version 3.0.2.

Here is the process I've gone through: 
(NOTE: when i say fail - i mean my magento install is now missing the app/Mage.php file and when i try access it over the web, i am redirected to the Downloader)

1. use only core-composer-installer with preconfigured local.xml as after script - works as expected.
2. add a modman package to composer - and composer update - works as expected
3. require composer-installer and composer update - works as expected
4. delete magento root and vendor folder and do composer install - works as expected
5. require "ebizmarts/magemonkey": “1.1.32” and composer update - works as expected
6. require "connect20/junaidbhura_mandrill” and composer update - works as expected
7. require "connect20/magento4u_customerattribute": “*” and composer update - works as expected
8. require "connect20/mt_switchcompare": “1.3” and composer update - fails!
9. remove "connect20/mt_switchcompare": “1.3” and composer update - returns to normal
10. require "colinmollenhour/modman": “1.12” and composer update - fails
11. remove "connect20/magento4u_customerattribute": “*” and require "colinmollenhour/modman": “1.12” and composer update - fails
12. remove “colinmollenhour/modman” and require "connect20/magento4u_customerattribute” and composer update - works as expected
13. require "floodedcodeboy/fcb_currency-converter" : “*” and composer update - fails
14. require "floodedcodeboy/magento-social-tiles" : “0.1.0” and composer update - returns to normal
15. require "connect20/mt_switchcompare": “1.3” and composer update - fails
16. remove "connect20/mt_switchcompare": “1.3” and composer update - fails

and below is my complete composer.json file: 

```
{
    "name": "floodedcodeboy/magento-shop",
    "description": "Magento Shop",
    "authors": [
        {
            "name": "floodedcodeboy",
            "email": "redacted@mail.com"
        }
    ],
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:bragento/magento-core.git"
        },
        {
           "type": "vcs",
           "url": "https://github.com/cotya/magento-composer-installer"
        },
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        {
            "type": "vcs",
            "url":  "git@github.com:floodedcodeboy/fcb_CurrencyConverter.git"
        },
        {
            "type": "vcs",
            "url":  "https://bitbucket.org/floodedcodeboy/magento-social-tiles.git"
        }
    ],
    "require": {
        "magento/core": "~1.9",
        "aydin-hassan/magento-core-composer-installer": "^1.2.2",
        "colinmollenhour/modman": "1.12",
        "magento-hackathon/magento-composer-installer": "3.0.2",
        "ebizmarts/magemonkey": "1.1.32",
        "connect20/junaidbhura_mandrill": "1.0.4",
        "connect20/magento4u_customerattribute": "*",
        "floodedcodeboy/fcb_currency-converter" : "*",
        "floodedcodeboy/magento-social-tiles" : "0.1.0"
    },
    "extra": {
        "magento-root-dir": "./htdocs",
        "modman-root-dir": ".modman",
        "magento-deploystrategy": "copy",
        "magento-core-deploy" : {
            "git-ignore-append": true
         },
         "auto-append-gitignore": true,
         "magento-force": true
    },
    "config": {
        "preferred-install": "dist"
    },
    "scripts": {
        "localconfig": "cp ./config/app/etc/local.xml ./htdocs/app/etc/",
    }
}
```

**Comment by AydinHassan** [comment] 2015-06-06 10:08
This is nothing to do with this plugin. This plugin is only working when you see output from it. It only does anything on updating/installing/removing packages with a type of "magento-core".

I've just reproduced this with your steps and can confirm the issue. I'm pretty sure it's either to do with the packages you are requiring and their dependency management or the module installer. 

First of all, try updating to the latest module installer, some changes to the patching process have happened recently.

After that you should investigate `connect20/magento4u_customerattribute` it seems to depend on the whole of Magento, and during installation, all of the Magento components for "1.9.0.1" are pulled down:

![screen shot 2015-06-06 at 10 39 48](https://cloud.githubusercontent.com/assets/2817002/8019170/781b48bc-0c38-11e5-9d78-f9aeda763ae8.png)

![screen shot 2015-06-06 at 10 40 57](https://cloud.githubusercontent.com/assets/2817002/8019172/8f04bdba-0c38-11e5-95af-640707227b4e.png)

Now remember you specifically required `magento/core` at `~1.9`, which brings in the latest version, at this time `1.9.1.1-patch2`.

If you check your `Mage.php` after installing `connect20/magento4u_customerattribute` the version is "1.9.0.1".

So it looks like something fucky is going on with the module installer, deploying the core packages that these modules depend on. I'm closing this for now, feel free to open if you find more evidence pointing towards a problem in this repo. But, if you look at the code, this plugin is not running at all when you are updating and removing packages with a type of `magento-module` or any connect packages.

**Closed by AydinHassan** 2015-06-06 10:08 UTC

**Comment by AydinHassan** [comment] 2015-06-06 10:22
I guess another way to rule out this package might be to not use it and just put a copy of magento in the root folder , and your modules and see if Mage.php still dissapears. I would try it but i'm a bit busy this weekend and my internet here is crap. Just took me like two hours to reproduce your steps because slow internet :(

**Comment by floodedcodeboy** [comment] 2015-06-06 12:11
Thank you for the second opinion! It's a huge help. I'm first going to investigate the `connect20/magento4u_customerattribute` module as that does seem funky that it's requiring `1.9.0.1` and would explain a few other issues i'm seeing.  I'm also a very busy this weekend. However again - thank you for having a look into this.
